const BAD_REQUEST = 400;

const NOT_FOUND = 404;

const SERVER_ERROR = 500;

const OK = 200;

const CREATED = 201;

const DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  BAD_REQUEST, NOT_FOUND, SERVER_ERROR, OK, CREATED, DUPLICATE_ERROR_CODE,
};
